[mypy]
python_version = 3.11
check_untyped_defs = True

[mypy-webrtcvad.*]
ignore_missing_imports = True

[mypy-faster_whisper.*]
ignore_missing_imports = True

[mypy-pyaudio.*]
ignore_missing_imports = True

[mypy-edge_tts.*]
ignore_missing_imports = True

[mypy-ollama.*]
ignore_missing_imports = True